apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io
  releaseName: crossplane
  version: 1.15.0
  values:
    args:
      - --debug
